let nome = prompt("qual seu nome ?  " )
 let numpedido = Number(prompt("qual o numero do seu pedido ?   "))
 const nomelanchonete ="lanchetech"
 let nomeproduto = prompt("qual produto você quer? ")
 let preco = number(prompt("qual o preço ?  "))
 let quantidade =number(prompt("quanto você quer ?  "))
 console.log("cliente: ", nome)
 console.log("numero: ", numpedido)
 console.log("produdo:  ", nomeproduto)
 console.log("valor:  ")
console.log("quantidade:  ",quantidade)